apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamentos
  labels:
    {{- include "alura-foods-app.labels" .| nindent 4}}
    app: pagamentos
spec:
  replicas: {{.Values.pagamentos.replicaCount}}
  selector:
    matchLabels:
      app: pagamentos
  template:
    metadata:
      labels:
        app: pagamentos
    spec:
      hostname: pagamentos-ms
      containers:
      - name: pagamentos
        image: {{.Values.pagamentos.image}}
        ports:
        - containerPort: {{.Values.pagamentos.port}} 
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configMap.name}}
              key: SERVER_HOST
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{.Values.configMap.name}}
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{.Values.configMap.name}}
              key: DB_USER
        - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
              name: {{.Values.secret.name}}
              key: mysql-root-password
